### ISSUE TITLE
Cardのチャイルド（pin-cotainer）にapplyRandomStylesの値をパスする方法

### ISSUE THREAD

**Issue by AndreiTMCIT** [adelppi/Kousensai-web#1]
元々のapplyRandomStyles()はCardのチャイルドのstyleは変更できない。
この方法でいいか確認してほしいです。

変更項目：
・applyRandomStyles()
https://github.com/adelppi/Kousensai-web/blob/ec9a95650088d3c8474c5a6283bc46cff85c1a17/frontend/src/views/Introduction.vue#L33-L57

・Introduction.vueのHTML
https://github.com/adelppi/Kousensai-web/blob/ec9a95650088d3c8474c5a6283bc46cff85c1a17/frontend/src/views/Introduction.vue#L73-L75

・Card.vue：
https://github.com/adelppi/Kousensai-web/blob/ec9a95650088d3c8474c5a6283bc46cff85c1a17/frontend/src/components/Card.vue#L69-L71

**Comment by adelppi** [comment]
その方法で合ってるけど、少しだけ修正した。
- Card.vueで`child_style`を受け取るので`props`に`child_style: String`を追加する必要があった
- randomな値の範囲を変えた

ありがとう！

![Screenshot 2023-09-16 at 10 30 14](https://github.com/adelppi/Kousensai-web/assets/49149861/4edaf6e2-1107-43c6-8801-f71cf39a1627)
