### ISSUE TITLE
LostFoundAdmin.vueでパスワードがあってなくても見れる

### ISSUE THREAD

**Issue by AndreiTMCIT** [adelppi/Kousensai-web#3]
[LostFoundAdmin.vue](https://github.com/adelppi/Kousensai-web/blob/125c9bec68b5912a8067e576d945efdeddda28e0/frontend/src/views/LostFoundAdmin.vue)

**Comment by adelppi** [comment]
対策したよ。
クエリと.envを読み取るコードがなぜか消し飛んでた...
危なかった🥶
